basic.forever(function () {
    music.playTone(262, music.beat(BeatFraction.Half))
    music.playTone(294, music.beat(BeatFraction.Half))
    basic.pause(50)
    music.playTone(349, music.beat(BeatFraction.Quarter))
    basic.pause(70)
    music.playTone(349, music.beat(BeatFraction.Quarter))
    basic.pause(70)
    music.playTone(349, music.beat(BeatFraction.Quarter))
    basic.pause(150)
    music.playTone(349, music.beat(BeatFraction.Quarter))
    basic.pause(100)
    music.playTone(349, music.beat(BeatFraction.Eighth))
    basic.pause(50)
    music.playTone(349, music.beat(BeatFraction.Quarter))
    basic.pause(100)
    music.playTone(349, music.beat(BeatFraction.Eighth))
    basic.pause(100)
    music.playTone(349, music.beat(BeatFraction.Eighth))
    basic.pause(200)
})
