def on_forever():
    music.play_tone(262, music.beat(BeatFraction.HALF))
    music.play_tone(294, music.beat(BeatFraction.HALF))
    basic.pause(50)
    music.play_tone(349, music.beat(BeatFraction.QUARTER))
    basic.pause(70)
    music.play_tone(349, music.beat(BeatFraction.QUARTER))
    basic.pause(70)
    music.play_tone(349, music.beat(BeatFraction.QUARTER))
    basic.pause(150)
    music.play_tone(349, music.beat(BeatFraction.QUARTER))
    basic.pause(100)
    music.play_tone(349, music.beat(BeatFraction.EIGHTH))
    basic.pause(50)
    music.play_tone(349, music.beat(BeatFraction.QUARTER))
    basic.pause(100)
    music.play_tone(349, music.beat(BeatFraction.EIGHTH))
    basic.pause(100)
    music.play_tone(349, music.beat(BeatFraction.EIGHTH))
    basic.pause(200)
basic.forever(on_forever)
